name: car_rental_for_customer
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.1.1
  dio: ^5.0.0
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  go_router: ^6.0.6
  infinite_scroll_pagination: ^3.2.0
  shared_preferences: ^2.0.17
  get_it: ^7.2.0
  nb_utils: ^5.0.5
  intl: ^0.18.0
  google_fonts: ^4.0.3
  smooth_page_indicator: ^1.0.1
  geolocator: ^9.0.2
  timeago: ^3.4.0
  cached_network_image: ^3.2.3
  flutter_dotenv: ^5.0.2
  google_maps_flutter: ^2.2.5
  firebase_messaging: ^14.4.0
  firebase_core: ^2.9.0
  flutter_local_notifications: ^13.0.0
  image_picker: ^0.8.7+1
  flutter_inappwebview: ^5.7.2+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
